Repository LibreBooking/docker, pull requests merged in 2023-09, with the labels that each got.

#56 Update RUN.md
  RUN.md
Labels: documentation

#59 Issue 58
  Dockerfile
  entrypoint.sh
Labels: enhancement

#61 issue-60: switch back to docker-php-ext-install
  Dockerfile
Labels: bug

#62 Keep github actions dependencies up to date
  .github/dependabot.yml
  .github/workflows/docker-publish.yml
Labels: enhancement

#67 Fix issue 65
  entrypoint.sh
Labels: bug
