Repository LibreBooking/docker, pull requests merged in 2023-04, with the labels that each got.

#10 Integration into the Librebooking organization
  .github/workflows/docker-publish.yml
  BUILD.md
  README.md
  RUN.md
  SETUP.md
Labels: documentation, enhancement

#12 Update Dockerfile
  Dockerfile
Labels: bug

#14 entrypoint.sh now sets the default timezone in config.php
  entrypoint.sh
Labels: enhancement

#17 Incremental enhancements
  BUILD.md
  Dockerfile
  entrypoint.sh
Labels: documentation, enhancement

#18 Adapt to librebooking v2.8.6
  Dockerfile
  SETUP.md
  entrypoint.sh
Labels: upgrade
